name: skein_rest_client
description: An abstraction layer for REST HTTP API
version: 0.0.7
homepage: https://github.com/skein-dart/skein_rest_client

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  meta: ^1.8.0
  async: ^2.9.0
  logging: ^1.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.6
  mockito:
  build_runner:
