name: skein_rest_client
description: An abstraction layer for REST HTTP API
version: 0.0.4
homepage: https://github.com/skein-dart/skein_rest_client

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  meta: ^1.7.0
  async: ^2.8.2
  logging: ^1.0.2

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.0
  mockito:
  build_runner:
